version: '3'

services:
  wiki:
    image: requarks/wiki:2
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: ${SERVICE_PASSWORD_WIKI}
      DB_NAME: wikijs
      PUID: 1000
      PGID: 1000
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - wiki-data:/wiki/data

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: wikijs
      POSTGRES_PASSWORD: ${SERVICE_PASSWORD_WIKI}
      POSTGRES_USER: wikijs
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  wiki-data:
  db-data: